name: Generate Snake Game GIF

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create dist folder (if not exists)
        run: mkdir -p dist  # Make sure dist exists

      - name: Generate Snake Game GIF
        uses: Platane/snk@master
        with:
          github_user_name: Rorspaws
          outputs: |
            dist/github-snake.gif

      - name: Push GIF to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
